# Generated by Django 4.2.16 on 2026-04-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('RSA', 'RSA'), ('AES', 'AES'), ('ECC', 'ECC'), ('DES', 'DES'), ('3DES', 'Triple DES'), ('ChaCha20', 'ChaCha20'), ('OTHER', 'Other')], max_length=20)),
                ('key_input', models.TextField(help_text='The key or seed to analyze')),
                ('key_length', models.IntegerField(default=0)),
                ('entropy_score', models.FloatField(default=0.0)),
                ('strength_score', models.IntegerField(default=0, help_text='0-100')),
                ('strength_label', models.CharField(default='Unknown', max_length=20)),
                ('patterns_found', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
